basicaly library is a collection of books in similarly libraries which is nothing but collection pricompiled code.
here libraries can use as shortcut by this way program space will be decreases and it can save the time. we have so many libraries in python like tensorflow,matplotlib,pandas, numpy,scipy...ect


numpy:num stands for number py stands for python.it is used in machine learning library.it consists mathematical functions
numpy is 50X faster than traditional python lists
for array object -ndarray



In [ ]:
import numpy
arr=numpy.array([1,2,3,4,5])
print(arr)


[1 2 3 4 5]


for shortcut we can use np like:


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


checking numpy version:

In [ ]:
import numpy as np
print(np.__version__)

1.23.5


Use a tuple to create a NumPy array:

In [1]:
import numpy as np
l1=(21,22,23,24,45,56,78)
b1=np.array(l1)
print(b1)

[21 22 23 24 45 56 78]


create a 1-D array containing the values:

In [2]:
import numpy as np
l1=[21,22,23,24,45,56,78]
b1=np.array(l1)
print(b1)

[21 22 23 24 45 56 78]


create a 2-D array containing the values:

In [3]:
import numpy as np
l1=[[21,22,23],[24,45,56]]
b1=np.array(l1)
print(b1)

[[21 22 23]
 [24 45 56]]


create a 3-D array containing the values:

In [4]:
import numpy as np
l1=[[21,22],[23,24],[45,56]]
b1=np.array(l1)
print(b1)

[[21 22]
 [23 24]
 [45 56]]


Check how many dimensions the arrays have:

In [13]:
import numpy as np
l1=np.array([21,22,23,24,45,56,78])
b1=np.array([[21,22,23],[24,45,56]])
c1=np.array([[21,22],[23,24]])
print(l1.ndim)
print(b1.ndim)
print(c1.ndim)


1
2
2
